create table contact (
  id                       bigint generated by default as identity,
  firstname                varchar(255),
  name                     varchar(255),
  birthdate                date,
  email                    varchar(255),
  
  constraint pk_task primary key (id))
;


